INSERT INTO resources (user_id, category_id, title, description, resource_url, thumbnail_url)
VALUES
(1, 1, 'Art Gallery of Alberta', 'Collecting is central to the Art Gallery of Alberta''s role as an active resource and research facility for the Alberta community and broader public. Since its founding in 1924, the AGA has acquired over 6,000 works of art, the vast majority of which were produced after 1950 and added to the Collection since 1970. The strength of the gallery''s contemporary collection lies primarily in the area of Canadian abstract painting and sculpture, with a strong emphasis on the work of artists from this region in the context of parallel national and international movements.', 'https://www.youraga.ca/', 'https://images.pexels.com/photos/2086361/pexels-photo-2086361.jpeg?auto=compress&cs=tinysrgb&h=300'),
(1, 1, 'MoMA', 'Museum of Modern Art', 'https://www.moma.org/', 'https://images.pexels.com/photos/2807495/pexels-photo-2807495.jpeg?auto=compress&cs=tinysrgb&h=300'),
(1, 2, 'Jun''s Kitchen', 'A relaxing cooking channel sharing popular Japanese recipes', 'https://www.youtube.com/channel/UCRxAgfYexGLlu1WHGIMUDqw', 'https://images.pexels.com/photos/6896514/pexels-photo-6896514.jpeg?auto=compress&cs=tinysrgb&h=300'),
(1, 3, 'Dribbble', 'Millions of designers and agencies around the world showcase their portfolio work on Dribbble - the home to the world''s best design and creative professionals.', 'https://dribbble.com/', 'https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&h=300'),
(1, 4, 'Financial Education Resources', 'An annotated list of Canadian and international websites that provide financial information, on topics such as inflation, banking, personal finances, investing and consumer protection.', 'https://www.bankofcanada.ca/about/educational-resources/financial-education-resources/', 'https://images.pexels.com/photos/4386158/pexels-photo-4386158.jpeg?auto=compress&cs=tinysrgb&h=300'),
(2, 5, 'Garden Design', 'Learn How to Garden', 'https://www.gardendesign.com/how-to/', 'https://images.pexels.com/photos/16254627/pexels-photo-16254627.jpeg?auto=compress&cs=tinysrgb&h=300'),
(2, 6, 'Be Healthy', 'Take a Spa Retreat!', 'https://www.sparklinghill.com/', 'https://images.pexels.com/photos/4916534/pexels-photo-4916534.jpeg?auto=compress&cs=tinysrgb&h=300'),
(2, 7, 'Language', 'Parlez-vous français?', 'https://www.rosettastone.com', 'https://images.pexels.com/photos/7450476/pexels-photo-7450476.jpeg?auto=compress&cs=tinysrgb&h=300'),
(3, 8, 'Marketing Is Everything', 'The 1990s will belong to the customer. And that is great news for the marketer. Technology is transforming choice, and choice is transforming the marketplace. As a result, we are witnessing the emergence of a new marketing paradigm—not a “do more” marketing that simply turns up the volume on the sales spiels of the past but a knowledge- and experience-based marketing that represents the once-and-for-all death of the salesman.', 'https://hbr.org/1991/01/marketing-is-everything', 'https://images.pexels.com/photos/6476587/pexels-photo-6476587.jpeg?auto=compress&cs=tinysrgb&h=300'),
(3, 9, 'The power of music: how it can benefit health', 'I think music in itself is healing, American musician Billy Joel once said. Its an explosive expression of humanity. Its something we are all touched by. No matter what culture we are from, everyone loves music.', 'https://www.medicalnewstoday.com/articles/302903', 'https://images.pexels.com/photos/13244401/pexels-photo-13244401.jpeg?auto=compress&cs=tinysrgb&h=300'),
(3, 10, 'NewScientist Technology', 'From the earliest stone tools to the latest advances in artificial intelligence, robotics, blockchains and virtual reality, technology has continuously transformed our lives. Stay informed about the latest technological breakthroughs and the ethical and societal norms they challenge.', 'https://www.newscientist.com/subject/technology/', 'https://images.pexels.com/photos/10556474/pexels-photo-10556474.jpeg?auto=compress&cs=tinysrgb&h=300'),
(3, 11, 'Search Engine', 'Google all the things!', 'https://www.google.com/', 'https://images.pexels.com/photos/6446709/pexels-photo-6446709.jpeg?auto=compress&cs=tinysrgb&h=300');
